language: python

# Use the new container-based Travis infrastructure.
sudo: false

branches:
  except:
    - /pyup\/.*/

# Make sure we are on Ubuntu 14.04
dist: trusty

# Cache pip packages. Explicitly name the pip-cache directory since we
# use a custom `install` step which annuls `cache: pip`.
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/py37

os:
  - linux

jobs:
  fast_finish: true
  include:
    # macOS is first to account for the delay in starting the build on macOS.
    # This prevents the build from hanging on macOS as the last job to finish
    # in a stage.

    - &test-pyinstaller
      stage: Test - PyInstaller
      python: 2.7
      script:
        # Run tests and speed them up by sending them to multiple CPUs.
        - export PYTHONPATH="$PWD:$PYTHONPATH"
        - echo $PYTHONPATH
        - >
          py.test -n 3 --maxfail 3
          tests/functional/test_import.py

    - <<: *test-pyinstaller
      python: 3.6

  allow_failures:
      # Just tests how PyInstaller performs with upcoming Python
      - python: "nightly"

addons:
  # Python packages should be installed by "pip" via the "test/requirements-library.txt" specification.
  apt:
    packages:
    # lxml dependencies.
    - libxml2-dev
    - libxslt1-dev
    # pyttsx dependencies.
    - libespeak1
    # SciPy dependencies.
    - gfortran
    - libatlas-base-dev

before_install:
  # Perform the manual steps on osx to install python3 and activate venv
  # Per http://steven.casagrande.io/articles/travis-ci-and-if-statements/,
  # ensure the build fails for statements in an ``if`` clause.
  - >
      if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
          brew update || travis_terminate 1;
          brew upgrade python || brew install python || travis_terminate 1;
          python3 -m venv venv || travis_terminate 1;
          source venv/bin/activate;
      fi

install:
  # Update pip.
  - python -m pip install -U pip setuptools wheel | cat

  # Install dependencies for tests.
  - pip install --progress-bar=off -U -r tests/requirements-tools.txt
  - >
    if [[ $TRAVIS_BUILD_STAGE_NAME == 'Test - libraries' ]] ; then
        pip install --progress-bar=off -U -r tests/requirements-libraries.txt || travis_terminate 1
    fi

  # Compile bootloader
  - cd bootloader
  - python waf distclean all
  - cd ..

  # Install PyInstaller.
  - pip install --progress-bar=off -e .

  # Make sure the help options print.
  - python -m pyinstaller -h


script:
  - true

notifications:
    irc:
        channels:
            - "irc.freenode.org#pyinstaller"
        use_notice: true
        # skip_join: true would require +n mode *not to be set on #pyinstaller
        skip_join: false
